namespace RestaurantsInNY.Models
{
    public class APIModel
    {
        public string menu_item_id { get; set; }
        public string year { get; set; }
        public string restaurant_item_name { get; set; }
        public string restaurant { get; set; }
        public string restaurant_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public string food_category { get; set; }
        public string serving_size { get; set; }
        public string serving_size_unit { get; set; }
        public string calories { get; set; }
        public string total_fat { get; set; }
        public string saturated_fat { get; set; }
        public string trans_fat { get; set; }
        public string cholesterol { get; set; }
        public string sodium { get; set; }
        public string carbohydrates { get; set; }
        public string protein { get; set; }
        public string sugar { get; set; }
        public string dietary_fiber { get; set; }
        public string calories_100g { get; set; }
        public string total_fat_100g { get; set; }
        public string saturated_fat_100g { get; set; }
        public string trans_fat_100g { get; set; }
        public string cholesterol_100g { get; set; }
        public string sodium_100g { get; set; }
        public string carbohydrates_100g { get; set; }
        public string protein_100g { get; set; }
        public string sugar_100g { get; set; }
        public string dietary_fiber_100g { get; set; }
        public string kids_meal { get; set; }
        public string limited_time_offer { get; set; }
        public string regional { get; set; }
        public string shareable { get; set; }
        /*public string Menu_Item_ID { get; set; }
        public string Year { get; set; }
        public string Restaurant_Item_Name { get; set; }
        public string restaurant { get; set; }
        public int Restaurant_ID { get; set; }
        public string Item_Name { get; set; }
        public string Item_Description { get; set; }
        public string Food_Category { get; set; }
        public int Serving_Size { get; set; }
        public string Serving_Size_text { get; set; }
        public string Serving_Size_Unit { get; set; }
        public string Serving_Size_household { get; set; }
        public int Calories { get; set; }
        public int Total_Fat { get; set; }
        public int Saturated_Fat { get; set; }
        public int Trans_Fat { get; set; }
        public int Cholesterol { get; set; }
        public int Sodium { get; set; }
        public string Potassium { get; set; }
        public int Carbohydrates { get; set; }
        public int Protein { get; set; }
        public int Sugar { get; set; }
        public int Dietary_Fiber { get; set; }
        public int Calories_100g { get; set; }
        public int Total_Fat_100g { get; set; }
        public int Saturated_Fat_100g { get; set; }
        public int Trans_Fat_100g { get; set; }
        public int Cholestrol_100g { get; set; }
        public int Sodium_100g { get; set; }
        public string Potassium_100g { get; set; }
        public int Carbohydrates_100g { get; set; }
        public int Protein_100g { get; set; }
        public int Sugar_100g { get; set; }
        public int Dietary_Fiber_100g { get; set; }
        public string Calories_text { get; set; }
        public string Total_Fat_text { get; set; }
        public string Saturated_Fat_text { get; set; }
        public string Trans_Fat_text { get; set; }
        public string Cholesterol_text { get; set; }
        public string Sodium_text { get; set; }
        public string Potassium_text { get; set; }
        public string Carbohydrates_text { get; set; }
        public string Protein_text { get; set; }
        public string Sugar_text { get; set; }
        public string Dietary_Fiber_text { get; set; }
        public int Kids_Meal { get; set; }
        public int Limited_Time_Offer { get; set; }
        public int Regional { get; set; }
        public int Shareable { get; set; }*/

    }
}
